version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: backup.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: root