version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
  ApplicationStart:
    - location: start_server.sh
      timeout: 300